# Generated by Django 3.2 on 2021-04-14 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=30, unique=True)),
                ('quiz_category', models.CharField(max_length=30)),
                ('quiz_difficulty', models.CharField(choices=[('ea', 'easy'), ('me', 'medium'), ('diff', 'difficult')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_User_Anaytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=250)),
                ('question_type', models.CharField(choices=[('multichoice', 'Multi Choice Question'), ('multiselect', 'Multi Select Question'), ('Bool', 'Boolean Question'), ('text', 'accept Text Question')], max_length=30)),
                ('question_options', models.JSONField()),
                ('answers', models.CharField(max_length=250)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
            ],
        ),
    ]
