# Generated by Django 3.2 on 2021-04-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='questions_answers',
            options={'verbose_name_plural': 'Question_Answers'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quiz_info'},
        ),
        migrations.AlterModelOptions(
            name='quiz_user_anaytics',
            options={'verbose_name_plural': 'Quiz_User_Anaytics'},
        ),
        migrations.AlterField(
            model_name='quiz_user_anaytics',
            name='score',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz_categories'),
        ),
    ]
