# Generated by Django 3.2 on 2021-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20210415_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz_categories',
            options={'verbose_name_plural': 'Quiz_Category'},
        ),
        migrations.AddField(
            model_name='questions_answers',
            name='answer_score',
            field=models.CharField(default='10', max_length=5),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_difficulty',
            field=models.CharField(choices=[('ea', 'Easy'), ('me', 'Medium'), ('diff', 'Expert')], max_length=30),
        ),
    ]
