# Generated by Django 3.2 on 2021-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20210417_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_answers',
            name='question_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_difficulty',
            field=models.CharField(max_length=30),
        ),
    ]
