# Generated by Django 3.2 on 2021-04-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_answers',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
