# Generated by Django 3.2 on 2021-04-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_questions_answers_is_attempted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_answers',
            name='is_attempted',
        ),
    ]
