# Generated by Django 3.2 on 2021-04-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_remove_questions_answers_is_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_answers',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_all_questions', to='Quiz.quiz'),
        ),
    ]
